services:
  - type: web
    name: plg-rpg-telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TZ
        value: Europe/Helsinki
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_BASE
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: MANAGER_IDS
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BROADCAST_CHAT_ID
        sync: false
